[phases.setup]
nixPkgs = ["python39", "pip", "postgresql"]

[phases.install]
cmds = [
  "pip install -r app/requirements.txt"
]

[phases.build]
cmds = [
  "echo 'Build completed'"
]

[start]
cmd = "cd app && python production_app.py"
